# Name of the workflow
name: Git Test

# Runs under the following condition
# Workflow can be triggered manually
on: workflow_dispatch

permissions: 
  contents: write

# Runs the following jobs
jobs:
  git_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout a single file
          sparse-checkout: |
            README.md
      - env:
          NUM: 1
        run: | 
          line=$(sed "${NUM}!d" README.md)
          if [[ "$line" == *"[x]"* ]]
          then
            echo "Updated README through Github Action" > README.md
            git config --global user.email "han.dhk.kim@gmail.com"
            git config --global user.name "Han-Kim-0811"
            git add README.md
            git commit -m "Updated README through Github Action"
            git push
          else
            echo "Checkbox not checked!"
          fi
          
