# Name of the workflow
name: Git Test

# Runs under the following condition
# Workflow can be triggered manually
on: workflow_dispatch

permissions: 
  contents: write

# Runs the following jobs
jobs:
  git_list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout a single file
          sparse-checkout: |
            README.md
      - run: | 
          echo "Updated README through Github Action" >> README.md
          git add README.md
          git commit -m "Updated README through Github Action"
          git push
