# Name of the workflow
name: Hello World

# Runs under the following condition
on:
  schedule:
  # Runs on 6:30 AM August 5th Saturday 
    - cron: '30 6 5 8 6'

# Runs the following jobs
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World!
  say_bye:
    needs: say_hello
    runs-on: ubuntu-latest
    steps:
      - run: echo Good Bye World!
  
