# Name of the workflow
name: Hello World

# Runs under the following condition
on:
  schedule:
  # runs every 5 mins
    - cron: '*/5 * * * *'

# Runs the following jobs
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World!
  say_bye:
    needs: say_hello
    runs-on: ubuntu-latest
    steps:
      - run: echo Good Bye World!
  
